# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mood_tracker?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

logging:
  level:
    cn.jun.dev: debug




